### ISSUE TITLE
Regarding Repository access

### ISSUE THREAD

**Issue by gauravm043** [software-engineering-project-1/computer-organisation-lab-exp6-team1#1]
@khushpreet-kaur 
Ma'am I think this team has got another project of Digital Logic Design Lab 1. Adder Circuit "Team16", 
I have checked other repositories for MIPS 2 project and they match with the allotted teams. We didn't get any access to any repository (I have raised this issue on moodle.iiit.ac.in as well). 
We are Team 6 and  we were allotted MIPS 2 experiment. Kindly look into this matter. Thanks :)

**Comment by khushpreet-kaur** [comment]
@gauravm043  Thanks for logging the issue. 
I have added your team to "computer-organisation-lab-exp6-team1" i.e MIPS Assembly Language Programming - 2 experiment, as per the project allotment document given by Bhavana.  
Adder circuit experiment of Digital logic design lab is assigned to Team 16. Sorry for the inconvenience.

**Comment by gauravm043** [comment]
@khushpreet-kaur Thanks :)

**Comment by khushpreet-kaur** [comment]
@gauravm043 Please close the issue, if it got resolved.
